/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hello_app;

import hello_lib.Library;

public class App {
    public String getGreeting() {
        Library library = new Library();
        System.out.println("Library = " + library.someLibraryMethod());
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
